# Generated by Django 2.1.7 on 2019-03-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190305_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='users',
            new_name='friends',
        ),
    ]
