# Generated by Django 2.1.7 on 2019-03-08 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20190308_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='friendList',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
